CREATE DATABASE QLDA;
GO

USE QLDA;
GO

CREATE TABLE PHONGBAN
(
    MAPB VARCHAR(5) NOT NULL PRIMARY KEY,
    TENPB NVARCHAR(50) NOT NULL,
    TRUONGPHONG VARCHAR(5) NOT NULL,
    NG_NHANCHUC DATE NOT NULL
);
GO

CREATE TABLE NHANVIEN
(
    MANV VARCHAR(5) NOT NULL PRIMARY KEY,
    HONV NVARCHAR(20) NOT NULL,
    TENLOT NVARCHAR(20),
    TENNV NVARCHAR(10) NOT NULL,
    NGAYSINH DATE NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    PHAI VARCHAR(5) NOT NULL,
    LUONG DECIMAL(10,2) NOT NULL,
    MAPB VARCHAR(5) NOT NULL,
    CONSTRAINT fk_NHANVIEN_PHONGBAN FOREIGN KEY (MAPB) REFERENCES PHONGBAN (MAPB)
);
GO

ALTER TABLE PHONGBAN
ADD CONSTRAINT fk_PHONGBAN_NHANVIEN FOREIGN KEY (TRUONGPHONG) REFERENCES NHANVIEN(MANV);
GO

CREATE TABLE THANNHAN
(
    MANV VARCHAR(5) NOT NULL,
    TENTN NVARCHAR(30) NOT NULL,
    PHAI VARCHAR(5) NOT NULL,
    NGAYSINH DATE,
    QUANHE NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_THANNHAN PRIMARY KEY (MANV, TENTN),
    CONSTRAINT FK_THANNHAN_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO

CREATE TABLE DDIEMPB
(
    MAPB VARCHAR(5) NOT NULL,
    DIADIEM NVARCHAR(100) NOT NULL,
    CONSTRAINT PK_DDIEMPB PRIMARY KEY (MAPB, DIADIEM),
    CONSTRAINT FK_DDIEMPB_PHONGBAN FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
);
GO

CREATE TABLE DEAN
(
    MADA VARCHAR(5) NOT NULL PRIMARY KEY,
    TENDA NVARCHAR(50) NOT NULL,
    DDIEM_DA NVARCHAR(100) NOT NULL,
    MAPB VARCHAR(5) NOT NULL,
    CONSTRAINT FK_DEAN_PHONGBAN FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB)
);
GO

CREATE TABLE PHANCONG
(
    MANV VARCHAR(5) NOT NULL,
    MADA VARCHAR(5) NOT NULL,
    THOIGIAN DECIMAL(5,1) NOT NULL,
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MANV, MADA),
    CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PHANCONG_DEAN FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
);
