CREATE DATABASE HotelManagement

GO
 
 USE HotelManagement

 GO

 CREATE TABLE KhachHang(
	MaKH INT IDENTITY(1,1) NOT NULL,
	CCCD VARCHAR(50) NOT NULL,
	SDT_KH VARCHAR(15) NOT NULL,
	GioiTinh NVARCHAR(10) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
	DiaChi NVARCHAR(100),
	QuocTich NVARCHAR(50),
	Email_KH VARCHAR(100),
	CONSTRAINT PK_KhachHang  PRIMARY KEY (MaKH)
 )

 CREATE TABLE NhanVien(
	MaNV INT IDENTITY(1,1) NOT NULL,
	CCCD VARCHAR(50) NOT NULL,
	HoTen NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10) NOT NULL,
	ChucVu NVARCHAR(50) NOT NULL,
	SDT_NV VARCHAR(15) NOT NULL,
	Email_NV VARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(100),
    SoBHYT VARCHAR(50),
    SoHopDong VARCHAR(50),
    NamBatDau INT NOT NULL,
    MaSoThueCaNhan VARCHAR(50) NOT NULL,
	CONSTRAINT PK_NV PRIMARY KEY (MaNV)
 )

 GO

 CREATE TABLE LichLam(
	MaNV INT NOT NULL,
	NgayLam DATE NOT NULL,
	CaLam NVARCHAR(20) NOT NULL,
	CONSTRAINT PK_LichLam PRIMARY KEY(MaNV, NgayLam),
	CONSTRAINT FK_LichLam_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
 )

 GO

  CREATE TABLE Luong(
	MaNV INT NOT NULL,
	MucLuong DECIMAL(10,0) NOT NULL,
	Thuong DECIMAL(10, 2),
	Phat DECIMAL(10, 2),
	PhuCap DECIMAL(10, 2),
	CONSTRAINT PK_Luong PRIMARY KEY (MaNV),
	CONSTRAINT FK_Luong_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
 )
 
GO

 CREATE TABLE LoaiPhong(
	MaLP INT IDENTITY(1,1) NOT NULL,
	TenLP NVARCHAR(50) NOT NULL,
	SucChua INT NOT NULL,
	SoGiuong INT NOT NULL,
	DienTich DECIMAL(5, 2),
	TienNghi NVARCHAR(100) NOT NULL,
	GiaMacDinh DECIMAL(10, 2) NOT NULL,
	CONSTRAINT PK_LoaiPhong PRIMARY KEY (MaLP)
);

GO

 CREATE TABLE Phong(
	MaP INT IDENTITY(1,1) NOT NULL,
	SoP VARCHAR(10) NOT NULL,
	MaLP INT NOT NULL,
	TrangThai NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_Phong PRIMARY KEY (MaP),
	CONSTRAINT FK_Phong FOREIGN KEY (MaLP) REFERENCES LoaiPhong(MaLP)
 )

 GO

CREATE TABLE DatPhong(
	MaDP INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	MaKH INT NOT NULL,
	MaP INT NOT NULL,
	MaLP INT NOT NULL,
	MaHD INT NOT NULL,
	NgayDat DATE NOT NULL,
	NgayNhan DATE NOT NULL,
	NgayTra DATE NOT NULL,
	SoLuongKhach INT NOT NULL,
	TrangThai_DP NVARCHAR(50) NOT NULL DEFAULT N'Trống',
	FOREIGN KEY (MaLP) REFERENCES LoaiPhong(MaLP),
	--FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD) ALTER sau do chưa có bản HoaDon
	CONSTRAINT FK_DatPhong_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
	CONSTRAINT FK_DatPhong_Phong FOREIGN KEY (MaP) REFERENCES Phong(MaP) ON DELETE CASCADE,
	CONSTRAINT FK_DatPhong_LoaiPhong FOREIGN KEY (MaLP) REFERENCES LoaiPhong(MaLP) ON DELETE CASCADE,
	CONSTRAINT UQ_DatPhong_MaP_NgayDat UNIQUE (MaP, NgayDat)
 )

 GO

 CREATE TABLE UuDai(
	MaUD INT NOT NULL,
	TenUD NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(100),
	PhanTramGiam DECIMAL(3,2) NOT NULL,
	NgayBD DATE NOT NULL,
	NgayKT DATE NOT NULL,
	DK_UD NVARCHAR(100),
	TrangThai_UD NVARCHAR(50) NOT NULL DEFAULT N'Không',
	CONSTRAINT PK_UuDai PRIMARY KEY (MaUD),
	CONSTRAINT CHK_NgayUD CHECK (NgayBD<NgayKT),
)

GO

CREATE TABLE HoaDon(
	MaHD INT NOT NULL,
	SoHD VARCHAR(50) NOT NULL,
	MaKH INT NOT NULL,
	MaDP INT NOT NULL,
	MaUD INT NOT NULL,
	MaNV INT IDENTITY(1,1) NOT NULL,
	NgayLapHD DATE NOT NULL,
	SL_Phong INT NOT NULL,
	DonGia DECIMAL(10,0) NOT NULL,
	TienPhi_DV DECIMAL(10, 2),
	TrangThai NVARCHAR(10) NOT NULL DEFAULT ('Chưa TT'),
	CONSTRAINT PK_HoaDon PRIMARY KEY (MaHD),
	CONSTRAINT FK_HoaDon_DatPhong FOREIGN KEY (MaDP) REFERENCES DatPhong(MaDP),
	CONSTRAINT FK_HoaDon_UuDai FOREIGN KEY (MaUD) REFERENCES UuDai(MaUD),
	CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
	CONSTRAINT FK_HoaDon_NV FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV)
)

GO

--thêm khóa ngoại còn thiếu cho bảng DatPhong 
ALTER TABLE DatPhong ADD CONSTRAINT FK_DatPhong_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD);

CREATE TABLE Mon(
	MaMon INT IDENTITY(1,1),
	TenMon NVARCHAR(100) NOT NULL,
	GiaMon SMALLMONEY NOT NULL,
	TrangThai_Mon VARCHAR(20) NOT NULL DEFAULT ('available'),
	CONSTRAINT PK_Mon PRIMARY KEY (MaMon)
)

GO

CREATE TABLE DatMon(
	MaDM INT IDENTITY(1,1),
	MaKH INT,
	MaMon INT,
	SL_Mon INT NOT NULL,
	SetThoiGian DATETIME NOT NULL,
	TrangThai_DM NVARCHAR(50) NOT NULL DEFAULT N'Trống',
	CONSTRAINT PK_DatMon PRIMARY KEY (MaDM),
	CONSTRAINT FK_DatMon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
	CONSTRAINT FK_DatMon_Mon FOREIGN KEY (MaMon) REFERENCES Mon(MaMon)
)

GO

CREATE TABLE DichVu(
	MaDV INT IDENTITY(1,1),
	TenDV NVARCHAR(100) NOT NULL,
	GiaDV DECIMAL(10, 2) NOT NULL,
	Loai_DV NVARCHAR(50) NOT NULL,
	Mota TEXT,
	CONSTRAINT PK_DichVu PRIMARY KEY (MaDV)
)

GO

CREATE TABLE SuDungDichVu(
	MaSDDV INT IDENTITY(1,1),
	MaDP INT,
	MaDV INT,
	SL_DV INT NOT NULL,
	NgaySD DATE NOT NULL,
	CONSTRAINT PK_SDDV PRIMARY KEY (MaSDDV, MaDP),
	CONSTRAINT FK_SDDV_DatPhong FOREIGN KEY (MaDP) REFERENCES DatPhong(MaDP),
	CONSTRAINT FK_SDDV_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV),
)
